name: sync-jd_scripts
on:
  workflow_dispatch:
  schedule:
    - cron: '*/15 0-16,22-23 * * *'
jobs:
  sync:
    runs-on: ubuntu-18.04
    if: github.repository == 'nxppru/qinglong'
    timeout-minutes: 2
    steps:     
    - name: Clone Master
      run: |
        git clone https://github.com/whyour/qinglong.git master
    - name: Push Master
      uses: ad-m/github-push-action@master
      with:
        directory: master
        github_token: ${{ secrets.PAT }}
        branch: master
    - name: Delete Workflow Runs
      uses: Mattraks/delete-workflow-runs@main
      with:
        token: ${{ secrets.PAT }}
        repository: ${{ github.repository }}
        retain_days: 1
        keep_minimum_runs: 0
